version: '3'

services:
  protein.api:
    build: .
    command: gunicorn protein.server:app -c settings_gunicorn.py
    networks:
      - protein-net
    ports:
      - 10080:8080
    volumes:
      - .:/opt/:rw
      - data:/opt/data

  mysql:
      image: mysql:5.7.17
      ports:
        - 0.0.0.0:3308:3306
      command:
        - --character-set-server=utf8
        - --collation-server=utf8_unicode_ci
        - --skip-character-set-client-handshake
      volumes:
        - mysql-data:/var/lib/mysql
        - ./dumps:/opt/dumps
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=protein_db
        - MYSQL_USER=puser
        - MYSQL_PASSWORD=puser
      networks:
        - protein-net

  redis:
    image: redis:4-alpine
    volumes:
    - redis-data:/data
    networks:
    - protein-net

networks:
  protein-net: {}

volumes:
  data: {}
  mysql-data: {}
  redis-data: {}